SELECT ID, NAME, COUNTRYCODE, DISTRICT, POPULATION 
FROM CITY
WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;

SELECT ID, CITY, STATE, LAT_N, LONG_W
FROM STATION
WHERE 

DECLARE @N INTEGER
DECLARE @N1 INTEGER

SELECT @N = COUNT(CITY) FROM STATION
SELECT @N1 = COUNT(DISTINCT CITY) FROM STATION

SELECT @N - @N1;